In [2]:
! pip3 install pandas

Defaulting to user installation because normal site-packages is not writeable
Collecting pandas
  Downloading pandas-2.3.3-cp39-cp39-macosx_11_0_arm64.whl (10.8 MB)
     |████████████████████████████████| 10.8 MB 481 kB/s eta 0:00:01
Collecting tzdata>=2022.7
  Downloading tzdata-2026.3-py2.py3-none-any.whl (348 kB)
     |████████████████████████████████| 348 kB 33.1 MB/s eta 0:00:01
Requirement already satisfied: numpy>=1.22.4 in /Users/deepika/Library/Python/3.9/lib/python/site-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/deepika/Library/Python/3.9/lib/python/site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1
  Downloading pytz-2026.3.post1-py2.py3-none-any.whl (508 kB)
     |████████████████████████████████| 508 kB 3.6 MB/s eta 0:00:01
Requirement already satisfied: six>=1.5 in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas) (1.15.0)
Installing collected packages: tzdata, pytz, pandas
Successfully installed pandas-2.3.3 pytz-2026.3.post1 tzdata-2026.3
WARNING: You are using pip version 21.2.4; however, version 26.0.1 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.

In [3]:
import pandas as pd
import numpy as np

In [4]:
restraunt_data = {
    "Table_No": [12, 14, 15],
    "Bill_Amount": [1250, 800, 2400],
    "Waiter_Name": ["AMit", "Priya","Rahul"]
}
df = pd.DataFrame(restraunt_data)
print(df)
print(type(df))

print(df["Bill_Amount"])
print(type[df["Bill_Amount"]])

   Table_No  Bill_Amount Waiter_Name
0        12         1250        AMit
1        14          800       Priya
2        15         2400       Rahul
<class 'pandas.core.frame.DataFrame'>
0    1250
1     800
2    2400
Name: Bill_Amount, dtype: int64
type[0    1250
1     800
2    2400
Name: Bill_Amount, dtype: int64]

In [8]:
total_bill= [4700,8000,1200,500]
s = pd.Series(total_bill,index=['mon','tue','wed','fri'])
print(s)
print(type(s))

mon    4700
tue    8000
wed    1200
fri     500
dtype: int64
<class 'pandas.core.series.Series'>

In [10]:
print(df.values)
print(type(df.values))

[[12 1250 'AMit']
 [14 800 'Priya']
 [15 2400 'Rahul']]
<class 'numpy.ndarray'>

In [12]:
# question 1
food_bill= [45,30,15,60]
y = pd.Series(food_bill,index=['Pizza','Burger','Pasta','Fries'])
print(y)

Pizza     45
Burger    30
Pasta     15
Fries     60
dtype: int64

In [ ]:
# question2 
food_data = {
    "Bill_Amount": [1250, 800, 2400],
    "Waiter_Name": ["AMit", "Priya","Rahul"]
}

In [14]:
df = pd.read_csv("tip.csv")

In [ ]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [16]:
print(df.head(2))

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3

In [17]:
print(df.head(20))

    total_bill   tip     sex smoker  day    time  size
0        16.99  1.01  Female     No  Sun  Dinner     2
1        10.34  1.66    Male     No  Sun  Dinner     3
2        21.01  3.50    Male     No  Sun  Dinner     3
3        23.68  3.31    Male     No  Sun  Dinner     2
4        24.59  3.61  Female     No  Sun  Dinner     4
5        25.29  4.71    Male     No  Sun  Dinner     4
6         8.77  2.00    Male     No  Sun  Dinner     2
7        26.88  3.12    Male     No  Sun  Dinner     4
8        15.04  1.96    Male     No  Sun  Dinner     2
9        14.78  3.23    Male     No  Sun  Dinner     2
10       10.27  1.71    Male     No  Sun  Dinner     2
11       35.26  5.00  Female     No  Sun  Dinner     4
12       15.42  1.57    Male     No  Sun  Dinner     2
13       18.43  3.00    Male     No  Sun  Dinner     4
14       14.83  3.02  Female     No  Sun  Dinner     2
15       21.58  3.92    Male     No  Sun  Dinner     2
16       10.33  1.67  Female     No  Sun  Dinner     3
17       16.29  3.71    Male     No  Sun  Dinner     3
18       16.97  3.50  Female     No  Sun  Dinner     3
19       20.65  3.35    Male     No  Sat  Dinner     3

In [18]:
print(df.tail(10))

     total_bill   tip     sex smoker   day    time  size
234       15.53  3.00    Male    Yes   Sat  Dinner     2
235       10.07  1.25    Male     No   Sat  Dinner     2
236       12.60  1.00    Male    Yes   Sat  Dinner     2
237       32.83  1.17    Male    Yes   Sat  Dinner     2
238       35.83  4.67  Female     No   Sat  Dinner     3
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [ ]:
df.sample()  # gives random value

     total_bill  tip   sex smoker  day    time  size
184       40.55  3.0  Male    Yes  Sun  Dinner     2

In [24]:
df.shape
print(df.columns)
print(type(df.columns))

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')
<class 'pandas.core.indexes.base.Index'>

In [26]:
df.info

<bound method DataFrame.info of      total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]>

In [27]:
df.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [31]:
print(df['day'].value_counts())

print(df['day'].unique())
print(df['day'].nunique())

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64
['Sun' 'Sat' 'Thur' 'Fri']
4